source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target :Gift4 do

pod 'AFNetworking', '1.3.3'
pod 'JSONAPI', '1.0.0-rc1'

end

target :Gift4Tests do
    
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    
end