source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target :Gift4 do

pod 'AFNetworking', '~> 2.5'

end

target :Gift4Tests do
    
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    
end